name: Comment Contact Information For Contributions

on:
  workflow_call:

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Determine if comment is needed
        id: check_comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            const context = github.context;
            let shouldComment = false;
            let isIssue = false;
            
            // For issues, always comment
            if (context.payload.issue) {
              shouldComment = true;
              isIssue = true;
            }
            // For PRs, only comment if from a fork
            else if (context.payload.pull_request) {
              shouldComment = context.payload.pull_request.head.repo.fork === true;
            }
            
            core.setOutput('is_issue', isIssue.toString());
            core.setOutput('should_comment', shouldComment.toString());

      - name: Add contact information comment
        if: steps.check_comment.outputs.should_comment == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            const issueNumber = context.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const isIssue = '${{ steps.check_comment.outputs.is_issue }}' === 'true'
            
            let documentationText = '';
            if (isIssue) {
              documentationText = '\nOur [documentation](https://docs.spacelift.io) may contain helpful information related to your issue\n';
            }
            
            const body = `
            # Thank you for your contribution!
            
            We've been notified of this ${isIssue ? 'issue' : 'pull request'} and will review it soon. We appreciate you helping to make Spacelift better!
            ${documentationText}
            **For Spacelift Customers:**
            - For fastest response, please use your dedicated Slack or Microsoft Teams channel
            - Or email us directly at `support@spacelift.io`
            `;
            
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issueNumber,
              body: body
            });